'use strict';
/**
 * Demo catalogue. Shared by src/seed.js (database records) and
 * tools/generate-assets.js (poster / backdrop artwork), so artwork and data
 * never drift apart.
 *
 * `art` describes how the offline SVG poster is drawn:
 *   style : slash | veil | sunny | blaze | storm | cosmic | neon | retro
 *   colors: [deep background, accent]
 */

const MOVIES = [
  {
    slug: 'jawan',
    title: 'Jawan',
    tagline: 'Ready. Aim. Fire.',
    status: 'now_playing',
    genres: ['Action', 'Thriller'],
    languages: ['Hindi', 'Tamil', 'Telugu'],
    formats: ['2D', 'IMAX 2D'],
    certificate: 'UA',
    runtime: 169,
    rating: 8.4,
    votes: 214_500,
    releaseDate: '2023-09-07',
    director: 'Atlee',
    cast: ['Shah Rukh Khan', 'Nayanthara', 'Vijay Sethupathi', 'Deepika Padukone'],
    synopsis:
      'A high-octane thriller about a man on a mission to right the wrongs of society, driven by a personal vendetta and a promise made long ago.',
    trailerUrl: 'https://www.youtube.com/embed/ZGY8aukhW-I',
    art: { style: 'slash', colors: ['#1B0406', '#E3231F'] },
    tierPrices: { sofa: 600, recliner: 600, platinum: 450, gold: 350, silver: 280 },
  },
  {
    slug: 'the-nun-ii',
    title: 'The Nun II',
    tagline: 'Sister Irene faces the demon again.',
    status: 'now_playing',
    genres: ['Horror', 'Mystery'],
    languages: ['English', 'Hindi'],
    formats: ['2D', '4DX'],
    certificate: 'A',
    runtime: 110,
    rating: 7.1,
    votes: 88_300,
    releaseDate: '2023-09-08',
    director: 'Michael Chaves',
    cast: ['Taissa Farmiga', 'Jonas Bloquet', 'Storm Reid', 'Anna Popplewell'],
    synopsis:
      'Four years after the events at the Romanian abbey, Sister Irene once again comes face to face with the demonic force Valak.',
    trailerUrl: 'https://www.youtube.com/embed/QF2MBIkxMZs',
    art: { style: 'veil', colors: ['#050405', '#C8A96B'] },
    tierPrices: { sofa: 500, recliner: 500, platinum: 400, gold: 300, silver: 250 },
  },
  {
    slug: 'hu-ane-tu',
    title: 'Hu ane Tu',
    tagline: 'Ek lagn, anek gadbad.',
    status: 'now_playing',
    genres: ['Comedy', 'Romance', 'Family'],
    languages: ['Gujarati'],
    formats: ['2D'],
    certificate: 'U',
    runtime: 132,
    rating: 7.8,
    votes: 12_400,
    releaseDate: '2023-11-24',
    director: 'Viral Shah',
    cast: ['Yash Soni', 'Aarohi Patel', 'Deeksha Joshi'],
    synopsis:
      'A warm-hearted Gujarati comedy about a wedding that spirals into delightful chaos when two very different families collide.',
    trailerUrl: 'https://www.youtube.com/embed/hu-ane-tu-trailer',
    art: { style: 'sunny', colors: ['#0F5FA6', '#FFC93C'] },
    tierPrices: { sofa: 450, recliner: 450, platinum: 350, gold: 280, silver: 220 },
  },
  {
    slug: 'fukrey-3',
    title: 'Fukrey 3',
    tagline: 'The fukras are back.',
    status: 'now_playing',
    genres: ['Comedy'],
    languages: ['Hindi'],
    formats: ['2D'],
    certificate: 'UA',
    runtime: 144,
    rating: 6.5,
    votes: 41_100,
    releaseDate: '2023-09-28',
    director: 'Mrighdeep Singh Lamba',
    cast: ['Pulkit Samrat', 'Varun Sharma', 'Richa Chadha', 'Manjot Singh'],
    synopsis:
      'Choocha, Hunny and the gang stumble into an election campaign and a water scam, with predictably ridiculous consequences.',
    trailerUrl: 'https://www.youtube.com/embed/BBCBjQMBw-c',
    art: { style: 'retro', colors: ['#12213D', '#37D6A0'] },
    tierPrices: { sofa: 480, recliner: 480, platinum: 380, gold: 300, silver: 230 },
  },
  {
    slug: 'oppenheimer',
    title: 'Oppenheimer',
    tagline: 'The world forever changes.',
    status: 'now_playing',
    genres: ['Drama', 'History', 'Thriller'],
    languages: ['English'],
    formats: ['IMAX 2D', '2D'],
    certificate: 'A',
    runtime: 181,
    rating: 8.9,
    votes: 512_900,
    releaseDate: '2023-07-21',
    director: 'Christopher Nolan',
    cast: ['Cillian Murphy', 'Emily Blunt', 'Robert Downey Jr.', 'Matt Damon'],
    synopsis:
      'The story of J. Robert Oppenheimer and the Manhattan Project - a portrait of genius, ambition and the terrible weight of consequence.',
    trailerUrl: 'https://www.youtube.com/embed/uYPbbksJxIg',
    art: { style: 'blaze', colors: ['#0B0705', '#FF7A1A'] },
    tierPrices: { sofa: 650, recliner: 650, platinum: 500, gold: 380, silver: 300 },
  },
  {
    slug: 'leo',
    title: 'Leo',
    tagline: 'Bloody sweet.',
    status: 'now_playing',
    genres: ['Action', 'Crime'],
    languages: ['Tamil', 'Hindi', 'Telugu'],
    formats: ['2D', 'IMAX 2D'],
    certificate: 'UA',
    runtime: 164,
    rating: 8.0,
    votes: 132_700,
    releaseDate: '2023-10-19',
    director: 'Lokesh Kanagaraj',
    cast: ['Vijay', 'Trisha', 'Sanjay Dutt', 'Arjun Sarja'],
    synopsis:
      'A mild-mannered cafe owner in the hills is forced to confront a violent past he has spent years trying to bury.',
    trailerUrl: 'https://www.youtube.com/embed/dGmqRsXbMOc',
    art: { style: 'neon', colors: ['#07131A', '#25E0C8'] },
    tierPrices: { sofa: 580, recliner: 580, platinum: 440, gold: 340, silver: 270 },
  },

  // ── Coming soon ────────────────────────────────────────────────────────────
  {
    slug: 'animal',
    title: 'Animal',
    tagline: 'A son. A father. A storm.',
    status: 'coming_soon',
    genres: ['Action', 'Drama'],
    languages: ['Hindi', 'Telugu', 'Tamil'],
    formats: ['2D', 'IMAX 2D'],
    certificate: 'A',
    runtime: 201,
    rating: 0,
    votes: 0,
    releaseDate: '2026-09-18',
    director: 'Sandeep Reddy Vanga',
    cast: ['Ranbir Kapoor', 'Rashmika Mandanna', 'Anil Kapoor', 'Bobby Deol'],
    synopsis:
      'A sprawling, violent saga of a son whose devotion to his father curdles into obsession, and the war it unleashes.',
    trailerUrl: 'https://www.youtube.com/embed/si-UrMqcbz4',
    art: { style: 'blaze', colors: ['#1A0500', '#FF3D00'] },
    tierPrices: { sofa: 620, recliner: 620, platinum: 480, gold: 360, silver: 290 },
  },
  {
    slug: 'kalki-2898-ad',
    title: 'Kalki 2898 AD',
    tagline: 'The hunt begins.',
    status: 'coming_soon',
    genres: ['Sci-Fi', 'Action', 'Mythology'],
    languages: ['Telugu', 'Hindi', 'Tamil'],
    formats: ['IMAX 3D', '3D', '2D'],
    certificate: 'UA',
    runtime: 181,
    rating: 0,
    votes: 0,
    releaseDate: '2026-10-02',
    director: 'Nag Ashwin',
    cast: ['Prabhas', 'Deepika Padukone', 'Amitabh Bachchan', 'Kamal Haasan'],
    synopsis:
      'In a dystopian future built on the ruins of myth, a bounty hunter is drawn into a prophecy that could remake the world.',
    trailerUrl: 'https://www.youtube.com/embed/5xFGjhBsRWg',
    art: { style: 'storm', colors: ['#060B14', '#7FA7D9'] },
    tierPrices: { sofa: 700, recliner: 700, platinum: 550, gold: 420, silver: 330 },
  },
  {
    slug: 'hanu-man',
    title: 'Hanu-Man',
    tagline: 'A hero rises in Anjanadri.',
    status: 'coming_soon',
    genres: ['Superhero', 'Fantasy', 'Action'],
    languages: ['Telugu', 'Hindi'],
    formats: ['3D', '2D'],
    certificate: 'UA',
    runtime: 158,
    rating: 0,
    votes: 0,
    releaseDate: '2026-09-25',
    director: 'Prasanth Varma',
    cast: ['Teja Sajja', 'Amritha Aiyer', 'Varalaxmi Sarathkumar'],
    synopsis:
      'A small-town slacker gains extraordinary powers and must become the protector his village has been praying for.',
    trailerUrl: 'https://www.youtube.com/embed/hanu-man-trailer',
    art: { style: 'cosmic', colors: ['#100A2E', '#FFB300'] },
    tierPrices: { sofa: 500, recliner: 500, platinum: 400, gold: 310, silver: 250 },
  },
  {
    slug: 'dunki',
    title: 'Dunki',
    tagline: 'Four friends. One border.',
    status: 'coming_soon',
    genres: ['Comedy', 'Drama'],
    languages: ['Hindi'],
    formats: ['2D'],
    certificate: 'UA',
    runtime: 161,
    rating: 0,
    votes: 0,
    releaseDate: '2026-10-16',
    director: 'Rajkumar Hirani',
    cast: ['Shah Rukh Khan', 'Taapsee Pannu', 'Vicky Kaushal', 'Boman Irani'],
    synopsis:
      'Four friends from a Punjab village chase the dream of a better life abroad, taking the perilous "donkey flight" route.',
    trailerUrl: 'https://www.youtube.com/embed/VW4XO-52ubE',
    art: { style: 'sunny', colors: ['#0B4F6C', '#F2A65A'] },
    tierPrices: { sofa: 550, recliner: 550, platinum: 420, gold: 320, silver: 260 },
  },
  {
    slug: 'salaar',
    title: 'Salaar',
    tagline: 'Loyalty is a weapon.',
    status: 'coming_soon',
    genres: ['Action', 'Drama'],
    languages: ['Telugu', 'Hindi', 'Kannada'],
    formats: ['IMAX 2D', '2D'],
    certificate: 'A',
    runtime: 175,
    rating: 0,
    votes: 0,
    releaseDate: '2026-11-06',
    director: 'Prashanth Neel',
    cast: ['Prabhas', 'Prithviraj Sukumaran', 'Shruti Haasan'],
    synopsis:
      'Two friends bound by a childhood promise find themselves on opposite sides of a brutal war for a lawless city.',
    trailerUrl: 'https://www.youtube.com/embed/salaar-trailer',
    art: { style: 'slash', colors: ['#0D0D0F', '#B08544'] },
    tierPrices: { sofa: 560, recliner: 560, platinum: 430, gold: 330, silver: 265 },
  },
];

/** Seat layout presets. gapAfter renders an aisle after those seat numbers. */
const LAYOUTS = {
  // Kingfisher Multiplex — Audi 1 "Kingfisher Ultra" (Screen 1).
  // Exact BookMyShow seat map: S (Sofa 9), R (Recliner 9),
  // A-C Platinum 14 seats, D-E Platinum 18 seats,
  // F-G Gold 18 seats, H Gold 16 seats, I-K Silver 16 seats.
  'kingfisher-ultra': [
    { row: 'S', seats: 9,  tier: 'sofa',     gapAfter: [4] },
    { row: 'R', seats: 9,  tier: 'recliner',  gapAfter: [6] },
    { row: 'A', seats: 14, tier: 'platinum',  gapAfter: [9] },
    { row: 'B', seats: 14, tier: 'platinum',  gapAfter: [9] },
    { row: 'C', seats: 14, tier: 'platinum',  gapAfter: [9] },
    { row: 'D', seats: 18, tier: 'platinum',  gapAfter: [9] },
    { row: 'E', seats: 18, tier: 'platinum',  gapAfter: [9] },
    { row: 'F', seats: 18, tier: 'gold',      gapAfter: [9] },
    { row: 'G', seats: 18, tier: 'gold',      gapAfter: [9] },
    { row: 'H', seats: 16, tier: 'gold',      gapAfter: [9] },
    { row: 'I', seats: 16, tier: 'silver',    gapAfter: [9] },
    { row: 'J', seats: 16, tier: 'silver',    gapAfter: [9] },
    { row: 'K', seats: 16, tier: 'silver',    gapAfter: [9] },
  ],
  // Kingfisher Multiplex — Audi 2 "Kingfisher Standard" (Screen 2).
  // Exact BookMyShow seat map: S (Sofa 9), R (Recliner 9),
  // A-D Platinum 15 seats, E-F Gold 18 seats, G-H Silver 18 seats.
  'kingfisher-standard': [
    { row: 'S', seats: 9,  tier: 'sofa',     gapAfter: [3] },
    { row: 'R', seats: 9,  tier: 'recliner',  gapAfter: [5] },
    { row: 'A', seats: 15, tier: 'platinum',  gapAfter: [9] },
    { row: 'B', seats: 15, tier: 'platinum',  gapAfter: [9] },
    { row: 'C', seats: 15, tier: 'platinum',  gapAfter: [9] },
    { row: 'D', seats: 15, tier: 'platinum',  gapAfter: [9] },
    { row: 'E', seats: 18, tier: 'gold',      gapAfter: [9] },
    { row: 'F', seats: 18, tier: 'gold',      gapAfter: [9] },
    { row: 'G', seats: 18, tier: 'silver',    gapAfter: [9] },
    { row: 'H', seats: 18, tier: 'silver',    gapAfter: [9] },
  ],
};

const CINEMAS = [
  {
    slug: 'kingfisher-multiplex',
    name: 'Kingfisher Multiplex',
    brand: 'Kingfisher',
    city: 'Ahmedabad',
    area: 'Satellite',
    address: 'Kingfisher Multiplex, Satellite Road, Ahmedabad',
    lat: 23.0300,
    lng: 72.5100,
    distanceKm: 3.5,
    rating: 4.5,
    facilities: ['Dolby Atmos', 'Sofa Seats', 'Recliners', 'Parking', 'Food Court', 'Wheelchair Access'],
    screens: [
      { name: 'Audi 1', format: '2D', soundSystem: 'Dolby Atmos', layout: 'kingfisher-ultra',
        prices: { sofa: 500, recliner: 500, platinum: 400, gold: 300, silver: 250 } },
      { name: 'Audi 2', format: '2D', soundSystem: 'Dolby 7.1', layout: 'kingfisher-standard',
        prices: { sofa: 500, recliner: 500, platinum: 400, gold: 300, silver: 250 } },
    ],
  },
  {
    slug: 'pvr-icon-phoenix',
    name: 'PVR ICON: Phoenix Mall',
    brand: 'PVR',
    city: 'Ahmedabad',
    area: 'Bopal',
    address: '3rd Floor, Phoenix Marketcity, Bopal Road, Ahmedabad 380058',
    lat: 23.0225,
    lng: 72.5714,
    distanceKm: 2.4,
    rating: 4.6,
    facilities: ['Dolby Atmos', 'Recliners', 'Parking', 'Food Court', 'Wheelchair Access'],
  },
  {
    slug: 'inox-cg-road',
    name: 'INOX: CG Road',
    brand: 'INOX',
    city: 'Ahmedabad',
    area: 'Navrangpura',
    address: 'City Gold Complex, CG Road, Navrangpura, Ahmedabad 380009',
    lat: 23.0333,
    lng: 72.5601,
    distanceKm: 5.1,
    rating: 4.3,
    facilities: ['Dolby 7.1', 'Cafe', 'Parking'],
  },
  {
    slug: 'cinepolis-alpha-one',
    name: 'Cinepolis: Alpha One',
    brand: 'Cinepolis',
    city: 'Ahmedabad',
    area: 'Vastrapur',
    address: 'Alpha One Mall, Vastrapur, Ahmedabad 380015',
    lat: 23.0395,
    lng: 72.53,
    distanceKm: 7.8,
    rating: 4.4,
    facilities: ['4DX', 'VIP Lounge', 'Valet Parking', 'Recliners'],
  },
  {
    slug: 'rajhans-cinemas',
    name: 'Rajhans Cinemas: Iscon',
    brand: 'Rajhans',
    city: 'Ahmedabad',
    area: 'Satellite',
    address: 'Iscon Mega Mall, Satellite Road, Ahmedabad 380015',
    lat: 23.0225,
    lng: 72.5,
    distanceKm: 9.2,
    rating: 4.1,
    facilities: ['Dolby 7.1', 'Snack Bar', 'Parking'],
  },
  {
    slug: 'miraj-cinemas-mumbai',
    name: 'Miraj Cinemas: Andheri',
    brand: 'Miraj',
    city: 'Mumbai',
    area: 'Andheri West',
    address: 'Infiniti Mall, Link Road, Andheri West, Mumbai 400053',
    lat: 19.1364,
    lng: 72.8296,
    distanceKm: 1.8,
    rating: 4.2,
    facilities: ['Dolby Atmos', 'Recliners', 'Food Court'],
  },
];

/** art selects the vector illustration drawn by tools/generate-assets.js. */
/**
 * Multiplex F&B Menu — all prices are the 30% discounted rate (default pricing).
 * Original MRP is stored in `mrp` for reference.
 */
const FOOD_ITEMS = [
  // ── Snacks ─────────────────────────────────────────────────────────────────
  {
    slug: 'grill-sandwich',
    imageUrl: 'https://images.unsplash.com/photo-1528735602780-2552fd46c7af?w=400&q=80&fm=jpg&fit=crop',
    name: 'Grill Sandwich',
    category: 'Snacks',
    price: 175,
    mrp: 250,
    art: 'sandwich',
    colors: ['#7C2D12', '#FDE68A'],
    popular: true,
    veg: true,
    description: 'Toasted grilled sandwich loaded with fresh veggies and cheese — a hot, satisfying bite.',
    size: 'Regular',
  },
  {
    slug: 'maggi-plain',
    imageUrl: 'https://images.unsplash.com/photo-1612929633738-8fe44f7ec841?w=400&q=80&fm=jpg&fit=crop',
    name: 'Maggi – Plain',
    category: 'Snacks',
    price: 98,
    mrp: 140,
    art: 'noodles',
    colors: ['#B45309', '#FDE68A'],
    popular: true,
    veg: true,
    description: 'Classic Maggi noodles cooked to perfection — simple, comforting and hot.',
    size: 'Regular',
  },
  {
    slug: 'maggi-masala',
    imageUrl: 'https://images.unsplash.com/photo-1585032226651-759b368d7246?w=400&q=80&fm=jpg&fit=crop',
    name: 'Maggi – Masala',
    category: 'Snacks',
    price: 119,
    mrp: 170,
    art: 'noodles',
    colors: ['#B45309', '#F97316'],
    popular: true,
    veg: true,
    description: 'Spiced-up Maggi with masala seasoning for an extra kick of flavour.',
    size: 'Regular',
  },
  {
    slug: 'paneer-tikka-pizza',
    imageUrl: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?w=400&q=80&fm=jpg&fit=crop',
    name: 'Paneer Tikka Pizza',
    category: 'Snacks',
    price: 279,
    mrp: 399,
    art: 'pizza',
    colors: ['#991B1B', '#FCD34D'],
    popular: true,
    veg: true,
    description: 'Tandoori-marinated paneer on a crispy pizza base with capsicum and mozzarella.',
    size: 'Regular',
  },
  {
    slug: 'french-fries',
    imageUrl: 'https://images.unsplash.com/photo-1573080496219-bb080dd4f877?w=400&q=80&fm=jpg&fit=crop',
    name: 'French Fries',
    category: 'Snacks',
    price: 140,
    mrp: 200,
    art: 'fries',
    colors: ['#D97706', '#FDE68A'],
    popular: true,
    veg: true,
    description: 'Crispy golden fries, salted and served hot — the perfect movie snack.',
    size: 'Regular',
  },
  {
    slug: 'sweetcorn',
    imageUrl: 'https://images.unsplash.com/photo-1551754655-cd27e38d2076?w=400&q=80&fm=jpg&fit=crop',
    name: 'Sweetcorn',
    category: 'Snacks',
    price: 140,
    mrp: 200,
    art: 'corn',
    colors: ['#92400E', '#FDE047'],
    popular: false,
    veg: true,
    description: 'Warm, buttered sweetcorn kernels — light and delicious.',
    size: 'Regular',
  },

  // ── Popcorn ────────────────────────────────────────────────────────────────
  {
    slug: 'popcorn-large',
    imageUrl: 'https://images.unsplash.com/photo-1585647347483-22b66260dfff?w=400&q=80&fm=jpg&fit=crop',
    name: 'Popcorn – Large',
    category: 'Popcorn',
    price: 140,
    mrp: 200,
    art: 'popcorn',
    colors: ['#B3151C', '#F5E3C0'],
    popular: true,
    veg: true,
    description: 'Freshly popped large-size popcorn — lightly salted and great for sharing.',
    size: 'Large',
  },
  {
    slug: 'popcorn-tub',
    imageUrl: 'https://images.unsplash.com/photo-1505686994434-e3cc5abf1330?w=400&q=80&fm=jpg&fit=crop',
    name: 'Popcorn – Tub',
    category: 'Popcorn',
    price: 175,
    mrp: 250,
    art: 'popcorn',
    colors: ['#7F1D1D', '#FBBF24'],
    popular: true,
    veg: true,
    description: 'Our biggest popcorn tub — ideal for the whole row. Never runs out.',
    size: 'Tub',
  },

  // ── Cold Beverages ─────────────────────────────────────────────────────────
  {
    slug: 'coldrink-450ml',
    imageUrl: 'https://images.unsplash.com/photo-1581636625402-29b2a704ef13?w=400&q=80&fm=jpg&fit=crop',
    name: 'Coldrink 450ml',
    category: 'Cold Beverages',
    price: 140,
    mrp: 200,
    art: 'cup',
    colors: ['#1E3A5F', '#93C5FD'],
    popular: true,
    veg: true,
    description: 'Chilled 450ml cold drink — the perfect companion to your popcorn.',
    size: '450 ml',
  },

  // ── Hot Beverages ──────────────────────────────────────────────────────────
  {
    slug: 'cardamom-tea',
    imageUrl: 'https://images.unsplash.com/photo-1571934811356-5cc061b6821f?w=400&q=80&fm=jpg&fit=crop',
    name: 'Cardamom Tea',
    category: 'Hot Beverages',
    price: 35,
    mrp: 50,
    art: 'tea',
    colors: ['#78350F', '#FDE68A'],
    popular: false,
    veg: true,
    description: 'Freshly brewed chai infused with fragrant cardamom — warm and soothing.',
    size: 'Regular',
  },
  {
    slug: 'cafe-latte',
    imageUrl: 'https://images.unsplash.com/photo-1541167760496-1628856ab772?w=400&q=80&fm=jpg&fit=crop',
    name: 'Café Latte',
    category: 'Hot Beverages',
    price: 42,
    mrp: 60,
    art: 'coffee',
    colors: ['#3F2A1D', '#C69C6D'],
    popular: false,
    veg: true,
    description: 'Espresso balanced with steamed milk — smooth, creamy and comforting.',
    size: 'Regular',
  },
  {
    slug: 'cafe-mocha',
    imageUrl: 'https://images.unsplash.com/photo-1572442388796-11668a67e53d?w=400&q=80&fm=jpg&fit=crop',
    name: 'Café Mocha',
    category: 'Hot Beverages',
    price: 56,
    mrp: 80,
    art: 'coffee',
    colors: ['#3B1F10', '#A16207'],
    popular: false,
    veg: true,
    description: 'Rich espresso blended with chocolate and steamed milk — a café classic.',
    size: 'Regular',
  },
  {
    slug: 'cappuccino',
    imageUrl: 'https://images.unsplash.com/photo-1534778101976-62847782c213?w=400&q=80&fm=jpg&fit=crop',
    name: 'Cappuccino',
    category: 'Hot Beverages',
    price: 70,
    mrp: 100,
    art: 'coffee',
    colors: ['#4B2C1A', '#D4A574'],
    popular: true,
    veg: true,
    description: 'Bold espresso topped with thick, velvety foam — a cinema favourite.',
    size: 'Regular',
  },
  {
    slug: 'hot-tea',
    imageUrl: 'https://images.unsplash.com/photo-1544787219-7f47ccb76574?w=400&q=80&fm=jpg&fit=crop',
    name: 'Hot Tea',
    category: 'Hot Beverages',
    price: 35,
    mrp: 50,
    art: 'tea',
    colors: ['#065F46', '#6EE7B7'],
    popular: false,
    veg: true,
    description: 'A simple, perfectly brewed cup of hot tea to warm you up.',
    size: 'Regular',
  },
  {
    slug: 'black-coffee',
    imageUrl: 'https://images.unsplash.com/photo-1510707577719-ae7c14805e3a?w=400&q=80&fm=jpg&fit=crop',
    name: 'Black Coffee',
    category: 'Hot Beverages',
    price: 49,
    mrp: 70,
    art: 'coffee',
    colors: ['#1C1917', '#78716C'],
    popular: false,
    veg: true,
    description: 'Strong, no-frills black coffee for those who like it pure and bold.',
    size: 'Regular',
  },
  {
    slug: 'hot-coffee',
    imageUrl: 'https://images.unsplash.com/photo-1497935586351-b67a49e012bf?w=400&q=80&fm=jpg&fit=crop',
    name: 'Hot Coffee',
    category: 'Hot Beverages',
    price: 42,
    mrp: 60,
    art: 'coffee',
    colors: ['#3F2A1D', '#A78BFA'],
    popular: false,
    veg: true,
    description: 'Classic hot coffee — smooth and freshly brewed.',
    size: 'Regular',
  },
  {
    slug: 'hot-chocolate',
    imageUrl: 'https://images.unsplash.com/photo-1542990253-0d0f5be5f0ed?w=400&q=80&fm=jpg&fit=crop',
    name: 'Hot Chocolate',
    category: 'Hot Beverages',
    price: 63,
    mrp: 90,
    art: 'shake',
    colors: ['#451A03', '#D97706'],
    popular: false,
    veg: true,
    description: 'Rich, velvety hot chocolate — a warm hug in a cup.',
    size: 'Regular',
  },

  // ── Combos ─────────────────────────────────────────────────────────────────
  {
    slug: 'movie-snack-combo',
    imageUrl: 'https://images.unsplash.com/photo-1603378703578-08b69d2e6a85?w=400&q=80&fm=jpg&fit=crop',
    name: 'Movie Snack Combo',
    category: 'Combos',
    price: 245,
    mrp: 350,
    art: 'combo',
    colors: ['#4C1D95', '#C4B5FD'],
    popular: true,
    veg: true,
    description: 'Popcorn Large + Coldrink 450ml — the quintessential movie duo. Save ₹35 vs buying separately.',
    size: 'Combo for 1',
  },
  {
    slug: 'sandwich-coffee-combo',
    imageUrl: 'https://images.unsplash.com/photo-1555507036-ab1f4038808a?w=400&q=80&fm=jpg&fit=crop',
    name: 'Sandwich & Coffee Combo',
    category: 'Combos',
    price: 189,
    mrp: 270,
    art: 'combo',
    colors: ['#064E3B', '#6EE7B7'],
    popular: true,
    veg: true,
    description: 'Grill Sandwich + Cappuccino — the perfect pre-show pick-me-up. Save ₹28 vs buying separately.',
    size: 'Combo for 1',
  },
  {
    slug: 'pizza-coldrink-combo',
    imageUrl: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=400&q=80&fm=jpg&fit=crop',
    name: 'Pizza & Coldrink Combo',
    category: 'Combos',
    price: 369,
    mrp: 599,
    art: 'combo',
    colors: ['#991B1B', '#FCD34D'],
    popular: true,
    veg: true,
    description: 'Paneer Tikka Pizza + Coldrink 450ml — a full meal deal. Save ₹50 vs buying separately.',
    size: 'Combo for 1',
  },
  {
    slug: 'snack-platter-combo',
    imageUrl: 'https://images.unsplash.com/photo-1576107232684-1279f390859f?w=400&q=80&fm=jpg&fit=crop',
    name: 'Snack Platter Combo',
    category: 'Combos',
    price: 349,
    mrp: 600,
    art: 'combo',
    colors: ['#78350F', '#FDE68A'],
    popular: false,
    veg: true,
    description: 'French Fries + Sweetcorn + Coldrink 450ml — great for sharing between two. Save ₹71 vs buying separately.',
    size: 'Combo for 2',
  },
  {
    slug: 'family-feast-combo',
    imageUrl: 'https://images.unsplash.com/photo-1536392706976-e486e2ba97af?w=400&q=80&fm=jpg&fit=crop',
    name: 'Family Feast Combo',
    category: 'Combos',
    price: 499,
    mrp: 800,
    art: 'combo',
    colors: ['#7F1D1D', '#FCA5A5'],
    popular: true,
    veg: true,
    description: 'Popcorn Tub + 2 Colddrinks + French Fries — feeds the whole row. Save ₹96 vs buying separately.',
    size: 'Combo for 3–4',
  },
  {
    slug: 'maggi-tea-combo',
    imageUrl: 'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=400&q=80&fm=jpg&fit=crop',
    name: 'Maggi & Tea Combo',
    category: 'Combos',
    price: 119,
    mrp: 190,
    art: 'combo',
    colors: ['#B45309', '#FDE68A'],
    popular: false,
    veg: true,
    description: 'Maggi Masala + Cardamom Tea — a comforting, budget-friendly combo. Save ₹15 vs buying separately.',
    size: 'Combo for 1',
  },
];

const OFFERS = [
  {
    slug: 'best-ticket-offers',
    title: 'Best Movie Ticket Offers',
    subtitle: 'Up to 50% off every Wednesday',
    code: 'CINEWED',
    discountType: 'percent',
    discountValue: 50,
    maxDiscount: 250,
    minAmount: 400,
    appliesTo: 'tickets',
    art: { style: 'reel', colors: ['#C1121F', '#E7E0C9'] },
  },
  {
    slug: 'popcorn-party',
    title: 'Popcorn Party',
    subtitle: 'Buy 1 jumbo tub, get 1 free',
    code: 'POPFREE',
    discountType: 'percent',
    discountValue: 25,
    maxDiscount: 200,
    minAmount: 350,
    appliesTo: 'food',
    art: { style: 'pop', colors: ['#7C1D6F', '#F9C74F'] },
  },
  {
    slug: 'first-show-flat',
    title: 'First Show, Flat ₹99',
    subtitle: 'Any show before 11 AM',
    code: 'EARLY99',
    discountType: 'flat',
    discountValue: 150,
    maxDiscount: 150,
    minAmount: 250,
    appliesTo: 'tickets',
    art: { style: 'dawn', colors: ['#1E3A8A', '#FDE68A'] },
  },
  {
    slug: 'combo-saver',
    title: 'Combo Saver Week',
    subtitle: 'Flat ₹120 off on all combos',
    code: 'COMBO120',
    discountType: 'flat',
    discountValue: 120,
    maxDiscount: 120,
    minAmount: 500,
    appliesTo: 'food',
    art: { style: 'pop', colors: ['#065F46', '#6EE7B7'] },
  },
  {
    slug: 'weekend-cashback',
    title: 'Weekend Cashback',
    subtitle: '10% back on 3+ tickets',
    code: 'WKND10',
    discountType: 'percent',
    discountValue: 10,
    maxDiscount: 300,
    minAmount: 600,
    appliesTo: 'all',
    art: { style: 'reel', colors: ['#4C1D95', '#DDD6FE'] },
  },
];

const GENRES = [
  'Action', 'Comedy', 'Drama', 'Horror', 'Thriller', 'Romance', 'Sci-Fi',
  'Fantasy', 'Mystery', 'Family', 'Crime', 'History', 'Superhero', 'Mythology',
];

const LANGUAGES = ['Hindi', 'English', 'Gujarati', 'Tamil', 'Telugu', 'Kannada', 'Marathi', 'Malayalam'];

const CITIES = ['Ahmedabad', 'Mumbai', 'Delhi NCR', 'Bengaluru', 'Pune', 'Surat', 'Hyderabad', 'Chennai'];

/** Daily show slots (24h) used to generate the rolling schedule. */
const SHOW_SLOTS = ['09:15', '12:30', '15:45', '17:30', '19:00', '22:15'];

module.exports = { MOVIES, LAYOUTS, CINEMAS, FOOD_ITEMS, OFFERS, GENRES, LANGUAGES, CITIES, SHOW_SLOTS };
