'use strict';
/**
 * Demo catalogue. Shared by src/seed.js (database records) and
 * tools/generate-assets.js (poster / backdrop artwork), so artwork and data
 * never drift apart.
 *
 * `art` describes how the offline SVG poster is drawn:
 *   style : slash | veil | sunny | blaze | storm | cosmic | neon | retro
 *   colors: [deep background, accent]
 */

const MOVIES = [
  {
    slug: 'jawan',
    title: 'Jawan',
    tagline: 'Ready. Aim. Fire.',
    status: 'now_playing',
    genres: ['Action', 'Thriller'],
    languages: ['Hindi', 'Tamil', 'Telugu'],
    formats: ['2D', 'IMAX 2D'],
    certificate: 'UA',
    runtime: 169,
    rating: 8.4,
    votes: 214_500,
    releaseDate: '2023-09-07',
    director: 'Atlee',
    cast: ['Shah Rukh Khan', 'Nayanthara', 'Vijay Sethupathi', 'Deepika Padukone'],
    synopsis:
      'A high-octane thriller about a man on a mission to right the wrongs of society, driven by a personal vendetta and a promise made long ago.',
    trailerUrl: 'https://www.youtube.com/embed/ZGY8aukhW-I',
    art: { style: 'slash', colors: ['#1B0406', '#E3231F'] },
  },
  {
    slug: 'the-nun-ii',
    title: 'The Nun II',
    tagline: 'Sister Irene faces the demon again.',
    status: 'now_playing',
    genres: ['Horror', 'Mystery'],
    languages: ['English', 'Hindi'],
    formats: ['2D', '4DX'],
    certificate: 'A',
    runtime: 110,
    rating: 7.1,
    votes: 88_300,
    releaseDate: '2023-09-08',
    director: 'Michael Chaves',
    cast: ['Taissa Farmiga', 'Jonas Bloquet', 'Storm Reid', 'Anna Popplewell'],
    synopsis:
      'Four years after the events at the Romanian abbey, Sister Irene once again comes face to face with the demonic force Valak.',
    trailerUrl: 'https://www.youtube.com/embed/QF2MBIkxMZs',
    art: { style: 'veil', colors: ['#050405', '#C8A96B'] },
  },
  {
    slug: 'hu-ane-tu',
    title: 'Hu ane Tu',
    tagline: 'Ek lagn, anek gadbad.',
    status: 'now_playing',
    genres: ['Comedy', 'Romance', 'Family'],
    languages: ['Gujarati'],
    formats: ['2D'],
    certificate: 'U',
    runtime: 132,
    rating: 7.8,
    votes: 12_400,
    releaseDate: '2023-11-24',
    director: 'Viral Shah',
    cast: ['Yash Soni', 'Aarohi Patel', 'Deeksha Joshi'],
    synopsis:
      'A warm-hearted Gujarati comedy about a wedding that spirals into delightful chaos when two very different families collide.',
    trailerUrl: 'https://www.youtube.com/embed/hu-ane-tu-trailer',
    art: { style: 'sunny', colors: ['#0F5FA6', '#FFC93C'] },
  },
  {
    slug: 'fukrey-3',
    title: 'Fukrey 3',
    tagline: 'The fukras are back.',
    status: 'now_playing',
    genres: ['Comedy'],
    languages: ['Hindi'],
    formats: ['2D'],
    certificate: 'UA',
    runtime: 144,
    rating: 6.5,
    votes: 41_100,
    releaseDate: '2023-09-28',
    director: 'Mrighdeep Singh Lamba',
    cast: ['Pulkit Samrat', 'Varun Sharma', 'Richa Chadha', 'Manjot Singh'],
    synopsis:
      'Choocha, Hunny and the gang stumble into an election campaign and a water scam, with predictably ridiculous consequences.',
    trailerUrl: 'https://www.youtube.com/embed/BBCBjQMBw-c',
    art: { style: 'retro', colors: ['#12213D', '#37D6A0'] },
  },
  {
    slug: 'oppenheimer',
    title: 'Oppenheimer',
    tagline: 'The world forever changes.',
    status: 'now_playing',
    genres: ['Drama', 'History', 'Thriller'],
    languages: ['English'],
    formats: ['IMAX 2D', '2D'],
    certificate: 'A',
    runtime: 181,
    rating: 8.9,
    votes: 512_900,
    releaseDate: '2023-07-21',
    director: 'Christopher Nolan',
    cast: ['Cillian Murphy', 'Emily Blunt', 'Robert Downey Jr.', 'Matt Damon'],
    synopsis:
      'The story of J. Robert Oppenheimer and the Manhattan Project - a portrait of genius, ambition and the terrible weight of consequence.',
    trailerUrl: 'https://www.youtube.com/embed/uYPbbksJxIg',
    art: { style: 'blaze', colors: ['#0B0705', '#FF7A1A'] },
  },
  {
    slug: 'leo',
    title: 'Leo',
    tagline: 'Bloody sweet.',
    status: 'now_playing',
    genres: ['Action', 'Crime'],
    languages: ['Tamil', 'Hindi', 'Telugu'],
    formats: ['2D', 'IMAX 2D'],
    certificate: 'UA',
    runtime: 164,
    rating: 8.0,
    votes: 132_700,
    releaseDate: '2023-10-19',
    director: 'Lokesh Kanagaraj',
    cast: ['Vijay', 'Trisha', 'Sanjay Dutt', 'Arjun Sarja'],
    synopsis:
      'A mild-mannered cafe owner in the hills is forced to confront a violent past he has spent years trying to bury.',
    trailerUrl: 'https://www.youtube.com/embed/dGmqRsXbMOc',
    art: { style: 'neon', colors: ['#07131A', '#25E0C8'] },
  },

  // ── Coming soon ────────────────────────────────────────────────────────────
  {
    slug: 'animal',
    title: 'Animal',
    tagline: 'A son. A father. A storm.',
    status: 'coming_soon',
    genres: ['Action', 'Drama'],
    languages: ['Hindi', 'Telugu', 'Tamil'],
    formats: ['2D', 'IMAX 2D'],
    certificate: 'A',
    runtime: 201,
    rating: 0,
    votes: 0,
    releaseDate: '2026-09-18',
    director: 'Sandeep Reddy Vanga',
    cast: ['Ranbir Kapoor', 'Rashmika Mandanna', 'Anil Kapoor', 'Bobby Deol'],
    synopsis:
      'A sprawling, violent saga of a son whose devotion to his father curdles into obsession, and the war it unleashes.',
    trailerUrl: 'https://www.youtube.com/embed/si-UrMqcbz4',
    art: { style: 'blaze', colors: ['#1A0500', '#FF3D00'] },
  },
  {
    slug: 'kalki-2898-ad',
    title: 'Kalki 2898 AD',
    tagline: 'The hunt begins.',
    status: 'coming_soon',
    genres: ['Sci-Fi', 'Action', 'Mythology'],
    languages: ['Telugu', 'Hindi', 'Tamil'],
    formats: ['IMAX 3D', '3D', '2D'],
    certificate: 'UA',
    runtime: 181,
    rating: 0,
    votes: 0,
    releaseDate: '2026-10-02',
    director: 'Nag Ashwin',
    cast: ['Prabhas', 'Deepika Padukone', 'Amitabh Bachchan', 'Kamal Haasan'],
    synopsis:
      'In a dystopian future built on the ruins of myth, a bounty hunter is drawn into a prophecy that could remake the world.',
    trailerUrl: 'https://www.youtube.com/embed/5xFGjhBsRWg',
    art: { style: 'storm', colors: ['#060B14', '#7FA7D9'] },
  },
  {
    slug: 'hanu-man',
    title: 'Hanu-Man',
    tagline: 'A hero rises in Anjanadri.',
    status: 'coming_soon',
    genres: ['Superhero', 'Fantasy', 'Action'],
    languages: ['Telugu', 'Hindi'],
    formats: ['3D', '2D'],
    certificate: 'UA',
    runtime: 158,
    rating: 0,
    votes: 0,
    releaseDate: '2026-09-25',
    director: 'Prasanth Varma',
    cast: ['Teja Sajja', 'Amritha Aiyer', 'Varalaxmi Sarathkumar'],
    synopsis:
      'A small-town slacker gains extraordinary powers and must become the protector his village has been praying for.',
    trailerUrl: 'https://www.youtube.com/embed/hanu-man-trailer',
    art: { style: 'cosmic', colors: ['#100A2E', '#FFB300'] },
  },
  {
    slug: 'dunki',
    title: 'Dunki',
    tagline: 'Four friends. One border.',
    status: 'coming_soon',
    genres: ['Comedy', 'Drama'],
    languages: ['Hindi'],
    formats: ['2D'],
    certificate: 'UA',
    runtime: 161,
    rating: 0,
    votes: 0,
    releaseDate: '2026-10-16',
    director: 'Rajkumar Hirani',
    cast: ['Shah Rukh Khan', 'Taapsee Pannu', 'Vicky Kaushal', 'Boman Irani'],
    synopsis:
      'Four friends from a Punjab village chase the dream of a better life abroad, taking the perilous "donkey flight" route.',
    trailerUrl: 'https://www.youtube.com/embed/VW4XO-52ubE',
    art: { style: 'sunny', colors: ['#0B4F6C', '#F2A65A'] },
  },
  {
    slug: 'salaar',
    title: 'Salaar',
    tagline: 'Loyalty is a weapon.',
    status: 'coming_soon',
    genres: ['Action', 'Drama'],
    languages: ['Telugu', 'Hindi', 'Kannada'],
    formats: ['IMAX 2D', '2D'],
    certificate: 'A',
    runtime: 175,
    rating: 0,
    votes: 0,
    releaseDate: '2026-11-06',
    director: 'Prashanth Neel',
    cast: ['Prabhas', 'Prithviraj Sukumaran', 'Shruti Haasan'],
    synopsis:
      'Two friends bound by a childhood promise find themselves on opposite sides of a brutal war for a lawless city.',
    trailerUrl: 'https://www.youtube.com/embed/salaar-trailer',
    art: { style: 'slash', colors: ['#0D0D0F', '#B08544'] },
  },
];

/** Seat layout presets. gapAfter renders an aisle after those seat numbers. */
const LAYOUTS = {
  standard: [
    { row: 'A', seats: 12, tier: 'regular', gapAfter: [3, 9] },
    { row: 'B', seats: 12, tier: 'regular', gapAfter: [3, 9] },
    { row: 'C', seats: 14, tier: 'regular', gapAfter: [4, 10] },
    { row: 'D', seats: 14, tier: 'regular', gapAfter: [4, 10] },
    { row: 'E', seats: 14, tier: 'premium', gapAfter: [4, 10] },
    { row: 'F', seats: 14, tier: 'premium', gapAfter: [4, 10] },
    { row: 'G', seats: 14, tier: 'premium', gapAfter: [4, 10] },
    { row: 'H', seats: 10, tier: 'vip', gapAfter: [5] },
  ],
  compact: [
    { row: 'A', seats: 10, tier: 'regular', gapAfter: [5] },
    { row: 'B', seats: 10, tier: 'regular', gapAfter: [5] },
    { row: 'C', seats: 12, tier: 'regular', gapAfter: [6] },
    { row: 'D', seats: 12, tier: 'premium', gapAfter: [6] },
    { row: 'E', seats: 12, tier: 'premium', gapAfter: [6] },
    { row: 'F', seats: 8, tier: 'vip', gapAfter: [4] },
  ],
  imax: [
    { row: 'A', seats: 16, tier: 'regular', gapAfter: [4, 12] },
    { row: 'B', seats: 16, tier: 'regular', gapAfter: [4, 12] },
    { row: 'C', seats: 18, tier: 'regular', gapAfter: [5, 13] },
    { row: 'D', seats: 18, tier: 'premium', gapAfter: [5, 13] },
    { row: 'E', seats: 18, tier: 'premium', gapAfter: [5, 13] },
    { row: 'F', seats: 18, tier: 'premium', gapAfter: [5, 13] },
    { row: 'G', seats: 12, tier: 'vip', gapAfter: [6] },
  ],
  // Kingfisher Multiplex — Audi 1 (Screen 1).
  // Exact BookMyShow seat map: S (Sofa 9), R (Recliner 9),
  // A-C Platinum 14 seats, D-E Platinum 18 seats,
  // F-H Gold 18 seats (H only 16), I-K Silver 16 seats.
  // gapAfter mirrors the aisle break shown on BookMyShow (after seat 4 for S, after 6 for R, after 9 for others).
  audi1: [
    { row: 'S', seats: 9,  tier: 'sofa',     gapAfter: [4] },
    { row: 'R', seats: 9,  tier: 'recliner',  gapAfter: [6] },
    { row: 'A', seats: 14, tier: 'platinum',  gapAfter: [9] },
    { row: 'B', seats: 14, tier: 'platinum',  gapAfter: [9] },
    { row: 'C', seats: 14, tier: 'platinum',  gapAfter: [9] },
    { row: 'D', seats: 18, tier: 'platinum',  gapAfter: [9] },
    { row: 'E', seats: 18, tier: 'platinum',  gapAfter: [9] },
    { row: 'F', seats: 18, tier: 'gold',      gapAfter: [9] },
    { row: 'G', seats: 18, tier: 'gold',      gapAfter: [9] },
    { row: 'H', seats: 16, tier: 'gold',      gapAfter: [9] },
    { row: 'I', seats: 16, tier: 'silver',    gapAfter: [9] },
    { row: 'J', seats: 16, tier: 'silver',    gapAfter: [9] },
    { row: 'K', seats: 16, tier: 'silver',    gapAfter: [9] },
  ],
  // Kingfisher Multiplex — Audi 2 (Screen 2).
  // Exact BookMyShow seat map: S (Sofa 9), R (Recliner 9),
  // A-D Platinum 15 seats, E-F Gold 18 seats, G-H Silver 18 seats.
  // gapAfter mirrors the aisle break: after seat 3 for S, after 5 for R, after 9 for all others.
  audi2: [
    { row: 'S', seats: 9,  tier: 'sofa',     gapAfter: [3] },
    { row: 'R', seats: 9,  tier: 'recliner',  gapAfter: [5] },
    { row: 'A', seats: 15, tier: 'platinum',  gapAfter: [9] },
    { row: 'B', seats: 15, tier: 'platinum',  gapAfter: [9] },
    { row: 'C', seats: 15, tier: 'platinum',  gapAfter: [9] },
    { row: 'D', seats: 15, tier: 'platinum',  gapAfter: [9] },
    { row: 'E', seats: 18, tier: 'gold',      gapAfter: [9] },
    { row: 'F', seats: 18, tier: 'gold',      gapAfter: [9] },
    { row: 'G', seats: 18, tier: 'silver',    gapAfter: [9] },
    { row: 'H', seats: 18, tier: 'silver',    gapAfter: [9] },
  ],
  // Legacy aliases kept so any existing DB screens referencing these names still render.
  grand: [],
  twin: [],
};

const CINEMAS = [
  {
    slug: 'kingfisher-multiplex',
    name: 'Kingfisher Multiplex',
    brand: 'Kingfisher',
    city: 'Ahmedabad',
    area: 'Satellite',
    address: 'Kingfisher Multiplex, Satellite Road, Ahmedabad',
    lat: 23.0300,
    lng: 72.5100,
    distanceKm: 3.5,
    rating: 4.5,
    facilities: ['Dolby Atmos', 'Sofa Seats', 'Recliners', 'Parking', 'Food Court', 'Wheelchair Access'],
    screens: [
      { name: 'Audi 1', format: '2D', soundSystem: 'Dolby Atmos', layout: 'audi1',
        prices: { sofa: 500, recliner: 500, platinum: 400, gold: 300, silver: 250 } },
      { name: 'Audi 2', format: '2D', soundSystem: 'Dolby 7.1', layout: 'audi2',
        prices: { sofa: 500, recliner: 500, platinum: 400, gold: 300, silver: 250 } },
    ],
  },
  {
    slug: 'pvr-icon-phoenix',
    name: 'PVR ICON: Phoenix Mall',
    brand: 'PVR',
    city: 'Ahmedabad',
    area: 'Bopal',
    address: '3rd Floor, Phoenix Marketcity, Bopal Road, Ahmedabad 380058',
    lat: 23.0225,
    lng: 72.5714,
    distanceKm: 2.4,
    rating: 4.6,
    facilities: ['Dolby Atmos', 'Recliners', 'Parking', 'Food Court', 'Wheelchair Access'],
    screens: [
      { name: 'Audi 1', format: 'IMAX 2D', soundSystem: 'IMAX 12.1', layout: 'imax' },
      { name: 'Audi 2', format: '2D', soundSystem: 'Dolby Atmos', layout: 'standard' },
      { name: 'Audi 3', format: '2D', soundSystem: 'Dolby 7.1', layout: 'compact' },
    ],
  },
  {
    slug: 'inox-cg-road',
    name: 'INOX: CG Road',
    brand: 'INOX',
    city: 'Ahmedabad',
    area: 'Navrangpura',
    address: 'City Gold Complex, CG Road, Navrangpura, Ahmedabad 380009',
    lat: 23.0333,
    lng: 72.5601,
    distanceKm: 5.1,
    rating: 4.3,
    facilities: ['Dolby 7.1', 'Cafe', 'Parking'],
    screens: [
      { name: 'Screen 1', format: '2D', soundSystem: 'Dolby Atmos', layout: 'standard' },
      { name: 'Screen 2', format: '4DX', soundSystem: 'Dolby 7.1', layout: 'compact' },
    ],
  },
  {
    slug: 'cinepolis-alpha-one',
    name: 'Cinepolis: Alpha One',
    brand: 'Cinepolis',
    city: 'Ahmedabad',
    area: 'Vastrapur',
    address: 'Alpha One Mall, Vastrapur, Ahmedabad 380015',
    lat: 23.0395,
    lng: 72.53,
    distanceKm: 7.8,
    rating: 4.4,
    facilities: ['4DX', 'VIP Lounge', 'Valet Parking', 'Recliners'],
    screens: [
      { name: 'Audi A', format: '3D', soundSystem: 'Dolby Atmos', layout: 'standard' },
      { name: 'Audi B', format: '2D', soundSystem: 'Dolby 7.1', layout: 'compact' },
      { name: 'VIP Audi', format: '2D', soundSystem: 'Dolby Atmos', layout: 'compact' },
    ],
  },
  {
    slug: 'rajhans-cinemas',
    name: 'Rajhans Cinemas: Iscon',
    brand: 'Rajhans',
    city: 'Ahmedabad',
    area: 'Satellite',
    address: 'Iscon Mega Mall, Satellite Road, Ahmedabad 380015',
    lat: 23.0225,
    lng: 72.5,
    distanceKm: 9.2,
    rating: 4.1,
    facilities: ['Dolby 7.1', 'Snack Bar', 'Parking'],
    screens: [
      { name: 'Screen 1', format: '2D', soundSystem: 'Dolby 7.1', layout: 'standard' },
      { name: 'Screen 2', format: '2D', soundSystem: 'Dolby 7.1', layout: 'compact' },
    ],
  },
  {
    slug: 'miraj-cinemas-mumbai',
    name: 'Miraj Cinemas: Andheri',
    brand: 'Miraj',
    city: 'Mumbai',
    area: 'Andheri West',
    address: 'Infiniti Mall, Link Road, Andheri West, Mumbai 400053',
    lat: 19.1364,
    lng: 72.8296,
    distanceKm: 1.8,
    rating: 4.2,
    facilities: ['Dolby Atmos', 'Recliners', 'Food Court'],
    screens: [
      { name: 'Audi 1', format: '2D', soundSystem: 'Dolby Atmos', layout: 'standard' },
      { name: 'Audi 2', format: '2D', soundSystem: 'Dolby 7.1', layout: 'compact' },
    ],
  },
];

/** art selects the vector illustration drawn by tools/generate-assets.js. */
const FOOD_ITEMS = [
  { slug: 'jumbo-popcorn', name: 'Jumbo Popcorn (Salted)', category: 'Popcorn', price: 350, art: 'popcorn', colors: ['#B3151C', '#F5E3C0'], popular: true, veg: true, description: 'Freshly popped, lightly salted - the classic tub built for sharing.', size: 'Large' },
  { slug: 'coca-cola-300', name: 'Coca Cola 300ml', category: 'Beverages', price: 180, art: 'cup', colors: ['#C8102E', '#FF4D4D'], popular: true, veg: true, description: 'Chilled Coca Cola served ice cold.', size: '300 ml' },
  { slug: 'french-fries', name: 'Peri Peri French Fries', category: 'Snacks', price: 220, art: 'fries', colors: ['#D97706', '#FDE68A'], popular: true, veg: true, description: 'Crispy golden fries tossed in peri peri seasoning.', size: 'Regular' },
  { slug: 'cheese-nachos', name: 'Loaded Cheese Nachos', category: 'Snacks', price: 300, art: 'nachos', colors: ['#92400E', '#FCD34D'], popular: true, veg: true, description: 'Corn nachos smothered in molten cheese sauce with jalapenos and salsa.', size: 'Regular' },
  { slug: 'chicken-burger', name: 'Crispy Chicken Burger', category: 'Meals', price: 340, art: 'burger', colors: ['#7C2D12', '#FBBF24'], popular: true, veg: false, description: 'Crunchy chicken patty, lettuce, cheese and smoky mayo in a toasted bun.', size: 'Single' },
  { slug: 'caramel-popcorn', name: 'Caramel Popcorn', category: 'Popcorn', price: 380, art: 'popcorn', colors: ['#78350F', '#FBBF24'], popular: false, veg: true, description: 'Kettle-cooked popcorn glazed in buttery caramel.', size: 'Large' },
  { slug: 'cheese-popcorn-combo', name: 'Cheese Popcorn + 2 Pepsi', category: 'Combos', price: 620, art: 'combo', colors: ['#4C1D95', '#C4B5FD'], popular: true, veg: true, description: 'Large cheese popcorn with two chilled 500ml Pepsi - our best value combo.', size: 'Combo for 2' },
  { slug: 'blueberry-shake', name: 'Blueberry Thick Shake', category: 'Beverages', price: 260, art: 'shake', colors: ['#312E81', '#818CF8'], popular: false, veg: true, description: 'Blended blueberries, vanilla ice cream and a whipped cream crown.', size: '400 ml' },
  { slug: 'cold-coffee', name: 'Cold Coffee', category: 'Beverages', price: 240, art: 'coffee', colors: ['#3F2A1D', '#C69C6D'], popular: false, veg: true, description: 'Slow-brewed coffee shaken with milk and ice.', size: '350 ml' },
  { slug: 'paneer-wrap', name: 'Tandoori Paneer Wrap', category: 'Meals', price: 310, art: 'wrap', colors: ['#166534', '#86EFAC'], popular: false, veg: true, description: 'Char-grilled paneer tikka rolled in a soft paratha with mint chutney.', size: 'Single' },
  { slug: 'choco-brownie', name: 'Molten Choco Brownie', category: 'Desserts', price: 280, art: 'brownie', colors: ['#451A03', '#D97706'], popular: false, veg: true, description: 'Warm fudge brownie with a molten centre and a scoop of vanilla.', size: 'Single' },
  { slug: 'samosa-pair', name: 'Punjabi Samosa (2 pc)', category: 'Snacks', price: 160, art: 'samosa', colors: ['#854D0E', '#FDE047'], popular: false, veg: true, description: 'Two hot samosas with tamarind and mint chutney.', size: '2 pieces' },
  { slug: 'family-combo', name: 'Family Feast Combo', category: 'Combos', price: 1290, art: 'combo', colors: ['#7F1D1D', '#FCA5A5'], popular: true, veg: false, description: '2 jumbo popcorn, 4 soft drinks, nachos and fries - feeds the whole row.', size: 'Combo for 4' },
  { slug: 'ice-tea', name: 'Peach Iced Tea', category: 'Beverages', price: 200, art: 'glass', colors: ['#9A3412', '#FDBA74'], popular: false, veg: true, description: 'Iced black tea with peach and a squeeze of lime.', size: '400 ml' },
];

const OFFERS = [
  {
    slug: 'best-ticket-offers',
    title: 'Best Movie Ticket Offers',
    subtitle: 'Up to 50% off every Wednesday',
    code: 'CINEWED',
    discountType: 'percent',
    discountValue: 50,
    maxDiscount: 250,
    minAmount: 400,
    appliesTo: 'tickets',
    art: { style: 'reel', colors: ['#C1121F', '#E7E0C9'] },
  },
  {
    slug: 'popcorn-party',
    title: 'Popcorn Party',
    subtitle: 'Buy 1 jumbo tub, get 1 free',
    code: 'POPFREE',
    discountType: 'percent',
    discountValue: 25,
    maxDiscount: 200,
    minAmount: 350,
    appliesTo: 'food',
    art: { style: 'pop', colors: ['#7C1D6F', '#F9C74F'] },
  },
  {
    slug: 'first-show-flat',
    title: 'First Show, Flat ₹99',
    subtitle: 'Any show before 11 AM',
    code: 'EARLY99',
    discountType: 'flat',
    discountValue: 150,
    maxDiscount: 150,
    minAmount: 250,
    appliesTo: 'tickets',
    art: { style: 'dawn', colors: ['#1E3A8A', '#FDE68A'] },
  },
  {
    slug: 'combo-saver',
    title: 'Combo Saver Week',
    subtitle: 'Flat ₹120 off on all combos',
    code: 'COMBO120',
    discountType: 'flat',
    discountValue: 120,
    maxDiscount: 120,
    minAmount: 500,
    appliesTo: 'food',
    art: { style: 'pop', colors: ['#065F46', '#6EE7B7'] },
  },
  {
    slug: 'weekend-cashback',
    title: 'Weekend Cashback',
    subtitle: '10% back on 3+ tickets',
    code: 'WKND10',
    discountType: 'percent',
    discountValue: 10,
    maxDiscount: 300,
    minAmount: 600,
    appliesTo: 'all',
    art: { style: 'reel', colors: ['#4C1D95', '#DDD6FE'] },
  },
];

const GENRES = [
  'Action', 'Comedy', 'Drama', 'Horror', 'Thriller', 'Romance', 'Sci-Fi',
  'Fantasy', 'Mystery', 'Family', 'Crime', 'History', 'Superhero', 'Mythology',
];

const LANGUAGES = ['Hindi', 'English', 'Gujarati', 'Tamil', 'Telugu', 'Kannada', 'Marathi', 'Malayalam'];

const CITIES = ['Ahmedabad', 'Mumbai', 'Delhi NCR', 'Bengaluru', 'Pune', 'Surat', 'Hyderabad', 'Chennai'];

/** Daily show slots (24h) used to generate the rolling schedule. */
const SHOW_SLOTS = ['09:15', '12:30', '15:45', '17:30', '19:00', '22:15'];

module.exports = { MOVIES, LAYOUTS, CINEMAS, FOOD_ITEMS, OFFERS, GENRES, LANGUAGES, CITIES, SHOW_SLOTS };
